In [ ]:
=====================Data Analysis==============================
1. Pandas                 - data frame analysis
2. Numpy                  - Numerical Analysis
3. matplotlib             - Graphs and plots
4. seaborn                - plots
5. bokhe                  - plots
6. plotly                 - plots

=====================Machine Learning============================
7. stats                  - for statistical model
8. scikit-learn (sklearn) - ML models

=====================Deep Learning==================================
8. OpenCV                 - Computer Vision
9. pillow                 - Image Operations
11. tensorflow            - Neutral Network Creations (developed by google)
12. keras                 - NN
13. pytourch              - alternative package of tensorflow(facebook meta)

=====================NLP=========================================
14. NL TK                 - Natural Language Toolkit
15. SpaCV                 - Alternative of NLTK
16. wordcloud             - most frequent occured words

=====================Scrapping===================================
17. SQlite                - Database Creation
18. Beautiful soup
19. Selenium

=======================API Creation==================================
20. Flask
21. Fast API
22. Gradio
23. Django

======================UI Creation========================================
24. Stramlit

=====================Transform Learning Model=================================
25. Mobilenet
26. Resnet
27. VGGnet
28. Inception
29. YOLO                    - Ultralytics

=======================Hugging face Transformers=================================
32. BERT                    - Bi Directional Encoder Represention of Transformers

=======================Allen NLP===========================================
33. Allen NLP packages

=======================GenAI============================================
34. Langchain
35. Google GeminiAI related Packgaes
36. OpenAI GPI related packages
37. Amazon BedRock related packages
38. Meta Llama Related Packages

========================Image and Video Generation==============================
39. GAN model related packages
40. SORA related packages

========================Model Deployment (MLOPs)===============================
41. mlflow using databrick
42. kuberflow (GCP account)

=========================Cloud application=====================================
43. Azure ML related packages
44. GCP VertexAI related packages
45. AWS Sagaemaker related packages

==========================small==========================
46. time
47. logging
48. math
49. random
50. env
51. os

**Step-1: Import Packages**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**Step-2 : Create DataFrame using list**

- data : your data either list or dict

- index : we need to provide list

- columns : we need to provide list

In [2]:
names = ['ramesh','suresh','satish']
pd.DataFrame(names)

        0
0  ramesh
1  suresh
2  satish

In [3]:
names = ['ramesh','suresh','satish']
pd.DataFrame(names,
            columns = ['Names'])
#pd.DataFrame(data,index,columns)

    Names
0  ramesh
1  suresh
2  satish

**Step-3 : Change the index**

In [6]:
names = ['ramesh','suresh','satish']
pd.DataFrame(names,index = ['a','b','c'],columns = ['Names'])

    Names
a  ramesh
b  suresh
c  satish

In [7]:
names = ['ramesh','suresh','satish']
idx = ['a','b','c']
cols = ['Names']
pd.DataFrame(names,index = idx,columns = cols)

    Names
a  ramesh
b  suresh
c  satish

**Step-4 : Add Multiple Columns**

In [3]:
names = ['ramesh','suresh','satish']
age = [20,22,24]
pd.DataFrame(zip(names,age))

        0   1
0  ramesh  20
1  suresh  22
2  satish  24

In [9]:
names = ['ramesh','suresh','satish']
age = [20,22,24]
pd.DataFrame(zip(names,age),columns = ['Name','Age'])

     Name  Age
0  ramesh   20
1  suresh   22
2  satish   24

**Step-5 : Create Empty Data and Update the columns**

In [10]:
#Empty DataFrame
df = pd.DataFrame()
df['Names'] = ['Ramesh','Suresh','Satish']
df['Age'] = [20,22,24]
df

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   24

**Step-6 : Add a new column with existing dataframe**

In [5]:
#updating
df = pd.DataFrame()
df['Names'] = ['Ramesh','Suresh','Satish']
df['Age'] = [20,22,24]
df['City'] = ['Hyd','Pune','Mumbai']
df

    Names  Age    City
0  Ramesh   20     Hyd
1  Suresh   22    Pune
2  Satish   24  Mumbai

**Step-7 : Override the Column Values**

- I want to override the age value

- originally age is 20,22,24

- new I want to update age = [30,32,34]

In [6]:
df['Age'] = [30,32,34] #'age' = new column will created
df

    Names  Age    City
0  Ramesh   30     Hyd
1  Suresh   32    Pune
2  Satish   34  Mumbai

In [7]:
df['age'] = [30,32,34] #'age' = new column will created
df

    Names  Age    City  age
0  Ramesh   30     Hyd   30
1  Suresh   32    Pune   32
2  Satish   34  Mumbai   34

**Step-8 : Drop the column**

- label

- axis

- index

- columns

- inplace

In [8]:
df

    Names  Age    City  age
0  Ramesh   30     Hyd   30
1  Suresh   32    Pune   32
2  Satish   34  Mumbai   34

In [9]:
df.drop('age') #error-axis by default 0 row

KeyError: "['age'] not found in axis"

In [15]:
df.drop('age',axis = 0) # error - axis=0 is rows

KeyError: "['age'] not found in axis"

In [16]:
df.drop('age',axis = 1) # axis = 1 (column)

    Names  Age    City
0  Ramesh   30     Hyd
1  Suresh   32    Pune
2  Satish   34  Mumbai

In [17]:
df # not override

    Names  Age    City  age
0  Ramesh   30     Hyd   30
1  Suresh   32    Pune   32
2  Satish   34  Mumbai   34

In [18]:
df #if we are able to use old column
#inpace will change

    Names  Age    City  age
0  Ramesh   30     Hyd   30
1  Suresh   32    Pune   32
2  Satish   34  Mumbai   34

In [11]:
# when ever we use columns labels no need of inplace
df.drop(columns = 'age',
       inplace = True)

    Names  Age    City
0  Ramesh   30     Hyd
1  Suresh   32    Pune
2  Satish   34  Mumbai

In [15]:
#index 2 drop
df.drop(index = 2)

    Names  Age  City
0  Ramesh   30   Hyd
1  Suresh   32  Pune

**Step-9 : Rename the Column**

In [ ]:
mapper: dict{'key':'value'}
index: 
columns: 
axis: 
copy: 
inplace:

In [21]:
#it will not show error it will print as it is
dict = {'City':'city'}
df.rename(dict)

    Names  Age    City
0  Ramesh   30     Hyd
1  Suresh   32    Pune
2  Satish   34  Mumbai

In [22]:
dict = {'City':'city'}
df.rename(columns = dict)

    Names  Age    city
0  Ramesh   30     Hyd
1  Suresh   32    Pune
2  Satish   34  Mumbai

In [23]:
dict = {'City':'city'}
df.rename(dict,axis=1)

    Names  Age    city
0  Ramesh   30     Hyd
1  Suresh   32    Pune
2  Satish   34  Mumbai

In [24]:
df

    Names  Age    City
0  Ramesh   30     Hyd
1  Suresh   32    Pune
2  Satish   34  Mumbai

In [25]:
dict = {'City':'city'}
df.rename(dict,axis=1,
         inplace = True)

In [26]:
df

    Names  Age    city
0  Ramesh   30     Hyd
1  Suresh   32    Pune
2  Satish   34  Mumbai

In [27]:
df.rename(index = {2:'b'})

    Names  Age    city
0  Ramesh   30     Hyd
1  Suresh   32    Pune
b  Satish   34  Mumbai

In [28]:
df.rename({2:'b'})

    Names  Age    city
0  Ramesh   30     Hyd
1  Suresh   32    Pune
b  Satish   34  Mumbai

In [17]:
df1 = pd.DataFrame()
df1['value'] = [i for i in range(1,10)]
df1['square_value'] = [i**2 for i in range(1,10)]
df1['cube_value'] = [i**3 for i in range(1,10)]
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

- len

- columns

- shape

- dtypes

- head

- tail

In [30]:
#Names of columns
df1.columns

Index(['value', 'square_value', 'cube_value'], dtype='object')

In [31]:
#convert into list
list(df1.columns)

['value', 'square_value', 'cube_value']

In [32]:
df1.columns.to_list()

['value', 'square_value', 'cube_value']

In [33]:
#Shape of dataframe (rows,cols)
df1.shape

(9, 3)

In [34]:
#data types of values
df1.dtypes
#interger = int
#float = float
#string = obj

value           int64
square_value    int64
cube_value      int64
dtype: object

In [35]:
#starting 5 values
df1.head()

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125

In [36]:
df1.head(2)

   value  square_value  cube_value
0      1             1           1
1      2             4           8

In [37]:
#Ending 5 values
df1.tail()

   value  square_value  cube_value
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [38]:
df1.tail(2)

   value  square_value  cube_value
7      8            64         512
8      9            81         729

In [39]:
len(df1)

9

In [40]:
df1.isnull()
# a null values are present or not
#True = NULL value Present
#False = NULL value Absent

   value  square_value  cube_value
0  False         False       False
1  False         False       False
2  False         False       False
3  False         False       False
4  False         False       False
5  False         False       False
6  False         False       False
7  False         False       False
8  False         False       False

In [41]:
df1.isnull().sum()
# column wise null value count will display

value           0
square_value    0
cube_value      0
dtype: int64

In [42]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   value         9 non-null      int64
 1   square_value  9 non-null      int64
 2   cube_value    9 non-null      int64
dtypes: int64(3)
memory usage: 348.0 bytes

**Step-10**

- How to change a specific value of a column

- df1.drop
    - either it will drop column or index
- df1.rename
    - either it will rename column or index
- df1.replace

In [43]:
#multiple data #but all data will replace
df1.replace({64:464})

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8           464         512
8      9            81         729

In [44]:
#one data #but all data will replace
df1.replace(64,464)

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8           464         512
8      9            81         729

**Step-11 : Selection of a Column**

In [45]:
df1['cube_value'].replace(64,464)

0      1
1      8
2     27
3    464
4    125
5    216
6    343
7    512
8    729
Name: cube_value, dtype: int64

In [46]:
df1['cube_value']
# Series
# Series looks like dataframe
#rows and columns

0      1
1      8
2     27
3     64
4    125
5    216
6    343
7    512
8    729
Name: cube_value, dtype: int64

In [47]:
type(df1)

pandas.core.frame.DataFrame

In [48]:
type(df1['cube_value'])

pandas.core.series.Series

In [49]:
df1.shape # 2D

(9, 3)

In [50]:
type(df1['cube_value'])

pandas.core.series.Series

In [51]:
df1['cube_value'].shape # 1D

(9,)

In [101]:
# Series is 1D
# DataFrame is 2D

In [52]:
df1[['cube_value']] # 2D

   cube_value
0           1
1           8
2          27
3          64
4         125
5         216
6         343
7         512
8         729

In [53]:
type(df1[['cube_value']]) # 2D

pandas.core.frame.DataFrame

In [54]:
# cube_value
#square_value
#multiple we are taking so we have take the list here and it will be list in list[['values_we_need_to_provide']]
# Muliple always keep those in list
df1[['cube_value','square_value']]

   cube_value  square_value
0           1             1
1           8             4
2          27             9
3          64            16
4         125            25
5         216            36
6         343            49
7         512            64
8         729            81

In [62]:
df1['cube_value'].replace(64,464)

0      1
1      8
2     27
3    464
4    125
5    216
6    343
7    512
8    729
Name: cube_value, dtype: int64

In [59]:
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8           464         512
8      9            81         729

**Step-12 : How to append a row**

In [ ]:
df1.loc[rows,columns]
df1.iloc[rows,cols]

# We can select particular rows and columns using a list : [start:stop:step]

In [19]:
df1.iloc[3:7,1:3]

   square_value  cube_value
3            16          64
4            25         125
5            36         216
6            49         343

In [64]:
df1.loc[3:7,['square_value','cube_value']]

   square_value  cube_value
3            16          64
4            25         125
5            36         216
6            49         343
7            64         512

In [65]:
cols = ['square_value','cube_value']
df1.loc[3:7,cols]

   square_value  cube_value
3            16          64
4            25         125
5            36         216
6            49         343
7            64         512

In [68]:
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [82]:
df1.iloc[[2,3,4]] #2DF

   value  square_value  cube_value
2      3             9          27
3      4            16          64
4      5            25         125

In [83]:
df1.iloc[[2]] #2D DF

   value  square_value  cube_value
2      3             9          27

In [86]:
df1.iloc[2] #1D  series

value            3
square_value     9
cube_value      27
Name: 2, dtype: int64

In [87]:
df1.iloc[[2,3,4],[0,2]]  #2D

   value  cube_value
2      3          27
3      4          64
4      5         125

In [88]:
df1.iloc[2,0] #1D series

3

In [77]:
df1.iloc[:,0]

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: value, dtype: int64

In [78]:
df1.iloc[2,:]

value            3
square_value     9
cube_value      27
Name: 2, dtype: int64

In [79]:
df1.iloc[[2],:]

   value  square_value  cube_value
2      3             9          27

In [80]:
df1.iloc[2:6,0]

2    3
3    4
4    5
5    6
Name: value, dtype: int64

In [81]:
df1.iloc[2:6,[0]]

   value
2      3
3      4
4      5
5      6

In [106]:
#loc

In [109]:
df1.loc[[2,3,4]]

   value  square_value  cube_value
2      3             9          27
3      4            16          64
4      5            25         125

In [110]:
df1.loc[[2]]

   value  square_value  cube_value
2      3             9          27

In [111]:
df1.loc[2]

value            3
square_value     9
cube_value      27
Name: 2, dtype: int64

In [113]:
df1.loc[[2,3,4],['value','square_value']]

   value  square_value
2      3             9
3      4            16
4      5            25

In [120]:
df1.loc[2,'value']

3

In [121]:
df1.loc[2,['value']]

value    3
Name: 2, dtype: int64

In [124]:
df1.loc[:,'value']

    value
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8
8       9
9      10
10     20

In [128]:
df1.loc[:,'value']

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    20
Name: value, dtype: int64

In [130]:
df1.loc[2,:]

value            3
square_value     9
cube_value      27
Name: 2, dtype: int64

In [136]:
df1.loc[[2],:]

   value  square_value  cube_value
2      3             9          27

In [144]:
df1.loc[2:6,'value']

2    3
3    4
4    5
5    6
6    7
Name: value, dtype: int64

In [145]:
df1.loc[2:6,['value']]

   value
2      3
3      4
4      5
5      6
6      7

**Step-13 : How to append a row**

In [89]:
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [90]:
df1.loc[9] = [10,100,100]

In [91]:
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729
9     10           100         100

In [23]:
ID = len(df1)
df1.loc[ID] = [20,200,2000]
df1

    value  square_value  cube_value
0       1             1           1
1       2             4           8
2       3             9          27
3       4            16          64
4       5            25         125
5       6            36         216
6       7            49         343
7       8            64         512
8       9            81         729
9      20           200        2000
ID     20           200        2000
11     20           200        2000

**Step-13 : How to save the dataframes**

In [ ]:
- we can save dataframe in two ways

- .csv

- .xlsx

- Where I want to save : directory

- What the filename to save: filename

- What is the type of file : extension

- different folder :"C:\Users\HP\Documents\FSDS GenAI & Agentic AI\Naresh IT\EDA\data1.csv"

- different folder :"C:\Users\HP\Documents\FSDS GenAI & Agentic AI\Naresh IT\EDA\data1.xlsx"

- same folder: ["data.csv" or "data.xlsx"]

In [96]:
csv_path = r"C:\Users\HP\Documents\FSDS GenAI & Agentic AI\Naresh IT\EDA\data1.csv"
excel_path = r"C:\Users\HP\Documents\FSDS GenAI & Agentic AI\Naresh IT\EDA\data1.xlsx"
df1.to_csv(csv_path)
df1.to_excel(excel_path)

In [97]:
csv_path = r"data1.csv"
excel_path = r"data1.xlsx"
df1.to_csv(csv_path) # index column created extra
df1.to_excel(excel_path) # index column created extra

**Step-14: Read the Dataset**

In [101]:
csv_path = r"data1.csv"
pd.read_csv(csv_path)

    Unnamed: 0  value  square_value  cube_value
0            0      1             1           1
1            1      2             4           8
2            2      3             9          27
3            3      4            16          64
4            4      5            25         125
5            5      6            36         216
6            6      7            49         343
7            7      8            64         512
8            8      9            81         729
9            9     10           100         100
10          10     20           200        2000

In [102]:
excel_path = r"data1.xlsx"
pd.read_excel(excel_path)

    Unnamed: 0  value  square_value  cube_value
0            0      1             1           1
1            1      2             4           8
2            2      3             9          27
3            3      4            16          64
4            4      5            25         125
5            5      6            36         216
6            6      7            49         343
7            7      8            64         512
8            8      9            81         729
9            9     10           100         100
10          10     20           200        2000

In [103]:
csv_path = r"data1.csv"
excel_path = r"data1.xlsx"
df1.to_csv(csv_path,index = False)  # it will delete the extra column
df1.to_excel(excel_path,index = False)  # it will delete the extra column

In [105]:
df1

    value  square_value  cube_value
0       1             1           1
1       2             4           8
2       3             9          27
3       4            16          64
4       5            25         125
5       6            36         216
6       7            49         343
7       8            64         512
8       9            81         729
9      10           100         100
10     20           200        2000

In [146]:
visa_df = r'Visadataset.csv'
bank_df = r'bank.csv'
pd.read_csv(visa_df)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [147]:
pd.read_csv(bank_df)

     age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0     30;"unemployed";"married";"primary";"no";1787;...
1     33;"services";"married";"secondary";"no";4789;...
2     35;"management";"single";"tertiary";"no";1350;...
3     30;"management";"married";"tertiary";"no";1476...
4     59;"blue-collar";"married";"secondary";"no";0;...
...                                                 ...
4516  33;"services";"married";"secondary";"no";-333;...
4517  57;"self-employed";"married";"tertiary";"yes";...
4518  57;"technician";"married";"secondary";"no";295...
4519  28;"blue-collar";"married";"secondary";"no";11...
4520  44;"entrepreneur";"single";"tertiary";"no";113...

[4521 rows x 1 columns]